=pod

=encoding utf8

=head1 DESCRIPTION

The release version 1.98 of L<Mojolicious> has dropped FastCGI support because
the code and test quality of the FastCGI code was not conforming to the rest
of L<Mojolicious>'s standards.

This code will now be maintained as a separate distribution, using the same
namespace as before, so installing it alongside L<Mojolicious> should give
You the same functionality as before.

=head1 REASONING

Other L<Mojolicious> users and I believe that FastCGI support is still
relevant today so the goal is to have this distribution synced with core
L<Mojolicious> and have the code and the tests improved so that eventually it
will be merged back in core L<Mojolicious>.

=head1 CONTRIBUTE

The maintainer of this distribution is Árpád Szász <arpad.szasz@plenum.ro>
and the code is maintained as a
L<Github repository|https://github.com/arpadszasz/mojo-server-fastcgi>.

=cut
